### ISSUE TITLE
outdated rdkit?

### ISSUE THREAD

**Issue by fmqeisfeld** [tbereau/auto_martini#2]
Hi, I've just installed automartini with all its dependencies. However, the following error is reported:

$ ./auto_martini --smi "N1=C(N)NN=C1N" --mol GUA

Traceback (most recent call last):
  File "./auto_martini", line 1181, in <module>
    listCGBeads,listBeadPos = findBeadPos(mol, feats, ringAtoms)
  File "./auto_martini", line 466, in findBeadPos
    trialEne  = evalGaussianInterac(mol, trialComb, ringAtomsFlat)
  File "./auto_martini", line 298, in evalGaussianInterac
    listBeads[i], ringAtoms)
  File "./auto_martini", line 261, in atomsInGaussian
    distBdAt = Chem.rdMolTransforms.GetBondLength(conf,i,beadId)
AttributeError: 'module' object has no attribute 'GetBondLength'

I've checked the Content of rdkit.Chem.rdMolTransforms and there's no function called GetBondLength(...). The only functions are:
CanonicalizeConformer,CanonicalizeMol,ComputeCanonicalTransform,ComputeCentroid and TransformConformer.

Coul you please update the source, cuz I really Need to parametrize MAH...I havent found any publications where it has already been parametrized according to the martini-ff.

regards,
frank.

**Comment by tbereau** [comment]
Hi Frank,

You need to update your version of RDKit. Look into your package manager. The more recent RDKit versions have the GetBondLength() function.

Best,
Tristan
