### ISSUE TITLE
Error run auto_martini 

### ISSUE THREAD

**Issue by georopon** [tbereau/auto_martini#21]
Hi have installed auto_martini and using following command: 
auto_martini --smi "N1=C(N)NN=C1N" --mol GUA 
get following file sanitize.log with followin erros: 
[16:32:27] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5

WARNING:__main__:Bad smiles format Nc1ncnn1 found
[16:32:27] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5

WARNING:__main__:Fixed smiles format to Nc1nnc[nH]1
WARNING:__main__:Error with BeautifulSoup constructor

AND NOT GET .*gro or *itp FILES. 

Please help me.

**Comment by tbereau** [comment]
The kekulize issues sound like you're using an old version of RDKIT. Maybe try to updating that.

For issues with "BeautifulSoup constructor," it's also likely that you're using an inappropriate version. Maybe try installing it with `pip` for instance. 

If these don't help, you can always try using either the `dev` branch (requires Python 3) or the `refactor` branch.

**Comment by tbereau** [comment]
Given your other comment I understand you've been able to run the code, so I'll close this issue.
