### ISSUE TITLE
how validate auto_martini  itp

### ISSUE THREAD

**Issue by georopon** [tbereau/auto_martini#22]
Please have this output: 
And i like know as can validate this parameter, i'have used smiles inputs more "--fpred" command 

; GENERATED WITH auto_martini.py
; 
; Tristan Bereau (2014)

[moleculetype]
; molname       nrexcl
  TDIM          2

[atoms]
; id    type    resnr   residue  atom    cgnr    charge  smiles
    1     P3      1     TDIM      P01     1         0   ; CO
    2     SN0     1     TDIM      S01     2         0   ; c1ccccc1
    3     C3      1     TDIM      C01     3         0   ; CC(C)C
    4     SNda    1     TDIM      S02     4         0   ; Oc1ccccc1
    5     SN0     1     TDIM      S03     5         0   ; c1ccccc1
    6     SP1     1     TDIM      S04     6         0   ; Cn1cc[n+]c1
    7     SQ0     1     TDIM      S05     7         1   ; C[n+]1ccnc1
    8     C5      1     TDIM      C02     8         0   ; CC
    9     C3      1     TDIM      C03     9         0   ; CCC
    10    C1      1     TDIM      C04     10        0   ; CCCC

[bonds]
; i j     funct     length    force.c.
  1 2       1         0.24     1250
  2 3       1         0.26     1250
  5 6       1         0.34     1250
  7 8       1         0.25     1250
  8 9       1         0.32     1250
  9 10       1         0.26     1250

[constraints]
;  i   j     funct   length
   2   4     1       0.24
   2   5     1       0.24
   4   5     1       0.24
   6   7     1       0.22

[angles]
; i j k         funct   angle   force.c.
  1 2 3         2       176.0   25.0
  1 2 4         2       121.7   25.0
  1 2 5         2       61.3    25.0
  2 5 6         2       117.1   25.0
  3 2 4         2       62.2    25.0
  3 2 5         2       122.6   25.0
  4 5 6         2       62.5    25.0
  5 6 7         2       121.4   25.0
  6 7 8         2       143.0   25.0
  7 8 9         2       127.9   25.0
  8 9 10         2       113.1   25.0

[dihedrals]
;  i     j    k    l   funct   angle  force.c.
   1     2    4    5       2     -0.5    10.0
   1     2    5    4       2     179.5   10.0
   1     5    2    4       2     -179.5   10.0
   1     5    4    2       2     0.5     10.0
   2     1    5    4       2     -0.5    10.0
   2     3    4    5       2     -1.1    10.0
   2     4    5    6       2     -152.8   10.0
   2     4    6    5       2     29.4    10.0
   2     5    4    3       2     1.2     10.0
   2     5    4    6       2     152.8   10.0
   2     5    6    4       2     -26.5   10.0
   3     2    4    5       2     178.9   10.0
   3     2    5    4       2     -1.2    10.0
   3     4    2    5       2     -178.9   10.0
   4     2    1    5       2     0.5     10.0
   4     2    5    6       2     27.1    10.0
   4     3    2    5       2     1.2     10.0
   5     2    4    6       2     -33.2   10.0

**Comment by tbereau** [comment]
How to validate a molecule is a scientific question. It depends on the problems you want to use this for. I would recommend you to look into the literature as to how best to do this.
