### ISSUE TITLE
Max. number of attempts: 54517

### ISSUE THREAD

**Issue by supernovaZhangJiaXing** [tbereau/auto_martini#27]
I tried to martinize coumarin 6 molecule (containing 25 atoms) with auto_martini. However, the program output the following information: 

> INFO:__main__:; Max. number of attempts: 54517
> INFO:__main__:; Atom partitioning: {0: 6, 1: 6, 2: 0, 3: 0, 4: 1, 5: 1, 6: 2, 7: 2, 8: 3, 9: 3, 10: 4, 11: 4, 12: 5, 13: 5, 14: 6, 15: 6, 16: 7, 17: 7, 18: 8, 19: 8, 20: 8, 21: 8, 22: 8, 23: 9, 24: 9}

and did not output the CG structure and topology of my molecule. 

My command:

`python auto_martini --smi "O=C1C(C2=NC(C=CC=C3)=C3S2)=Cc4c(O1)cc(N(CC)CC)cc4" --mol COU --cg COU_CG.gro --aa COU_AA.gro -v`

The molecular structure of coumarin 6 was at

> https://www.frontiersci.com/product/coumarin-6-98/

I used auto_martini with Python 2.7 in Anaconda 3, on Windows 10 operating system.

**Comment by tbereau** [comment]
It's not clear whether it's because the molecule is too large (with 25 heavy atoms I would instead recommend you work with smaller fragments), or whether something else is happening. Are you able to coarse-grain small test molecules? See Readme file for instance.
