### ISSUE TITLE
TypeError: No registered converter was able to produce a C++ rvalue of type std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > from this Python object of type NoneType

### ISSUE THREAD

**Issue by filipsPL** [tbereau/auto_martini#3]
Hi,
auto_martini works fine for an example smiles. But I can't convert any sdf files. I've tried to use sdf with guanazole (attached) but this results in errors:

```
./auto_martini --sdf gua-3D.sdf --mol DUPA --verbose
; ring atoms: [[0, 1, 3, 4, 5]]
; Heavy atoms: N C N N N C N 
; [0] -27.8905921889
; [1] -34.1904545745
; [3] -28.3426150603
; [4] -24.8125930713
; [5] -37.4331878925
; [0, 3] -63.2728078673
; [0, 4] -62.3127221936
; [1, 4] -65.7449246813
; [1, 5] -72.926702717
; [3, 5] -67.0298714638
; CG bead: 1
; CG bead: 5
;      with energy: -72.926702717
; Max. number of attempts: 4
; Atom partitioning: {0: 0, 1: 0, 2: 0, 3: 0, 4: 1, 5: 1, 6: 1}
Traceback (most recent call last):
  File "./auto_martini", line 1203, in <module>
    ringAtomsFlat, True)
  File "./auto_martini", line 825, in printAtoms
    molFrag = genMoleculeSMI(smiFrag)
  File "./auto_martini", line 89, in genMoleculeSMI
    mol = Chem.MolFromSmiles(args.smi)
TypeError: No registered converter was able to produce a C++ rvalue of type std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > from this Python object of type NoneType
```

~~Sample sdf files attached.~~
sdf files are here in gist:
https://gist.github.com/filipsPL/e1a7be4b989e50a4b10f

**Comment by tbereau** [comment]
Hi,

Can you try to convert your SDF file to a smiles string? Openbabel will do
that for you. Otherwise I'll have a look next week.

Best,
Tristan

**Comment by filipsPL** [comment]
Thanks,
That would probably be ok. However I would like to preserve 3D structure of the ligand (if it is possible), so sdf structure is a must.

**Comment by tbereau** [comment]
Hi,

I've tested your 2 SDF files on my computer, and there's no error. My guess is that your version of RDKit is too old. Can you check which version you have, and possibly try to update it?

````
In [1]: from rdkit import rdBase

In [2]: rdBase.rdkitVersion
Out[2]: '2013.09.1'

````

Best,
Tristan

**Comment by filipsPL** [comment]
(Un)fortunatelly I've upgraded the RDKit recently:

```
In [1]: from rdkit import rdBase

In [2]: rdBase.rdkitVersion
Out[2]: '2015.03.1'
```

Maybe the RDKit is too new :question:

**Comment by filipsPL** [comment]
(Un)fortunatelly I've upgraded the RDKit recently:

```
In [1]: from rdkit import rdBase

In [2]: rdBase.rdkitVersion
Out[2]: '2015.03.1'
```

Maybe the RDKit is too new :question:

**Comment by tbereau** [comment]
I'll try to update on my end to a more recent version of RDKit, but in the
meantime, see if you can create a virtual environment (conda or virtualenv)
with an older RDKit.

Best,
Tristan

**Comment by filipsPL** [comment]
Ok, I will try it with a virtualenv.

**Comment by filipsPL** [comment]
I've set up virtualenv with the same rdkit version as your:
```
>>> from rdkit import rdBase
>>> rdBase.rdkitVersion
'2013.09.1'
```

and run `(venv)fs@card:~/auto_martini$ ./auto_martini --sdf gua-3D.sdf --mol DUPA --verbose` This time the error is different than it was before:

```
; ring atoms: [[0, 1, 3, 4, 5]]
; Heavy atoms: N C N N N C N 
; [0] -27.8905921889
; [1] -34.1904545745
; [3] -28.3426150603
; [4] -24.8125930713
; [5] -37.4331878925
; [0, 3] -63.2728078673
; [0, 4] -62.3127221936
; [1, 4] -65.7449246813
; [1, 5] -72.926702717
; [3, 5] -67.0298714638
; CG bead: 1
; CG bead: 5
;      with energy: -72.926702717
; Max. number of attempts: 4
; Atom partitioning: {0: 0, 1: 0, 2: 0, 3: 0, 4: 1, 5: 1, 6: 1}
Traceback (most recent call last):
  File "./auto_martini", line 1206, in <module>
    ringAtomsFlat, True)
  File "./auto_martini", line 828, in printAtoms
    molFrag = genMoleculeSMI(smiFrag)
  File "./auto_martini", line 92, in genMoleculeSMI
    mol = Chem.MolFromSmiles(args.smi)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolfiles.MolFromSmiles(NoneType)
did not match C++ signature:
    MolFromSmiles(std::string SMILES, bool sanitize=True, boost::python::dict replacements={})
```

**Comment by tbereau** [comment]
Hmm. What's your boost version?

http://askubuntu.com/questions/147474/how-can-i-find-boost-version

**Comment by filipsPL** [comment]
```
dpkg -s libboost-dev | grep 'Version'
Version: 1.48.0.2
```

**Comment by tbereau** [comment]
I use 1.54. Can you try to upgrade your version of Boost? It looks like the
error is taking place when RDKit tries to use the Boost library. You should
be able to do this in a virtual environment relatively painlessly. I know
conda can install boost easily.

**Comment by filipsPL** [comment]
Thanks, now I have boost: 1.55 `Version: 1.55.0-1ppa1~precise1` and still the same error:
```
Traceback (most recent call last):
  File "./auto_martini", line 1206, in <module>
    ringAtomsFlat, True)
  File "./auto_martini", line 828, in printAtoms
    molFrag = genMoleculeSMI(smiFrag)
  File "./auto_martini", line 92, in genMoleculeSMI
    mol = Chem.MolFromSmiles(args.smi)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolfiles.MolFromSmiles(NoneType)
did not match C++ signature:
    MolFromSmiles(std::string SMILES, bool sanitize=True, boost::python::dict replacements={})
```

Any further ideas? Meanwhile I will try to install auto_martini on another "fresh" computer and see if it is possible.

**Comment by tbereau** [comment]
Oh ok, then try to change of branch:

````
git checkout refactor
python auto_martini.py --sdf gua-3D.sdf --mol DUPA --verbose
````
it's not a release branch yet, but it fixes some problems we have with
reading in some SMILES string within the code.

Cheers,
Tristan

**Comment by filipsPL** [comment]
Ok, this works fine. Thanks!

**Comment by tbereau** [comment]
@Alka00 I've never seen this error, but it seems to be linked to RDKit. Maybe have a look at your RDKit installation. If needed, please get in touch with their support.
