### ISSUE TITLE
The CG model for ethanol is different from the original paper

### ISSUE THREAD

**Issue by zhenzey** [tbereau/auto_martini#36]
Thanks for the nice tool! I have tried to use "auto_martini" to create a CG model for ethanol. The code CG the molecule as P1 bead type while the original paper gives it as P2 bead. Could you maybe explain the reason for it? Thanks a lot!

**Comment by tbereau** [comment]
Sorry for the super late reply! The parametrization was changed slightly to improve a bit the parametrization of a couple molecules. See the Supporting Material of https://doi.org/10.1063/1.5119101
