### ISSUE TITLE
No Metadata for AutoMartini

### ISSUE THREAD

**Issue by achenie** [tbereau/auto_martini#40]
I have encountered this problem as I was trying to access AutoMartini directory on Google Colab:
"PackageNotFoundError: No package metadata was found for auto_martini". Is there a work around? Better yet is there a pip or apt-get installation for AutoMartini? Thank you.

This gives more detail:
[/usr/lib/python3.10/importlib/metadata/__init__.py](https://localhost:8080/#) in from_name(cls, name)
    546                 return dist
    547         else:
--> 548             raise PackageNotFoundError(name)
    549 
    550     @classmethod

PackageNotFoundError: No package metadata was found for auto_martini

**Comment by tbereau** [comment]
I've never tried auto-martini in Google Colab, so I can't really help you. If you manage to fix it, please consider submitting a PR!

**Comment by HopeLynx** [comment]
Is there any news on getting it working in colab?

**Comment by anabiman** [comment]
With Google Colab you're just using an online jupyter notebook ... so one way you can do a pip install is by running from your notebook:
```bash
!pip install git+https://github.com/tbereau/auto_martini
```
This should enable you to import `auto_martini` from your notebook. Alternatively, I could upload a wheel to pypi for a simpler pip install, but there hasn't been any demand.

**Comment by HopeLynx** [comment]
My man, you are a hero, I've been fighting with conda enviroments etc like past 16 hours and there was oneliner to make it possible to work with.... Very appresiated

**Comment by anabiman** [comment]
Glad it worked. [PR49](https://github.com/tbereau/auto_martini/pull/49) improves installation instructions with pip.
