### ISSUE TITLE
Meets ValueError when testing example molecules

### ISSUE THREAD

**Issue by supernovaZhangJiaXing** [tbereau/auto_martini#41]
The auto_martini meets ValueError when testing example molecules, e.g. gua.
I found the ValueError occurs in numpy version 1.24, and I tried to fix it by changing the numpy version in pyproject.toml from `numpy = ">=1.23.1"` to `numpy = "==1.23.1"`, and thus changed the Error to warning. But it may not be the best method.
This method works to gua, but when it comes to my own molecule (part of NLG, SMILE: C12=CC=CC=C1C3=CN=CN3C2), the resulting itp rushed into blow-up of MD trajectory. I cannot confirm if this action derives from the above changes I have made.

**Comment by tbereau** [comment]
I don't recall getting this error. Can you provide more detail about the ValueError message?

Regarding the blow-up, it's likely because you're parametrizing an aromatic molecule with many constraints--these tend to be sensitive and may require careful equilibration (or fine-tuning of the parametrization with virtual sites, for instance).

**Comment by supernovaZhangJiaXing** [comment]
I just followed the instructions to configure auto_martini, and the resulting numpy version is 1.24.x by default.
Then if I run `poetry shell -C /path/to/my/auto_martini` and then run `python -m auto_martini --smi "N1=C(N)NN=C1N" --mol GUA --top GUA.itp`, it showed as following:
```
Traceback (most recent call last):
File "<frozen runpy>", line 198, in run module as main
File "<frozen runpy>", line 88, in run code
File "/run/media/Programs/auto martini/auto martini/auto martini/ main .py", line 129, in <module>
cg = solver.Cg_molecule(mol, args.molname args.topfname, args .forcepred)
File "/run/media/Programs/auto martini/auto martini/auto martini/solver.py", line 128, in __init__
list cg beads, list beadpos = optinization.find bead pos(
File "auto martini/optimization.pyx", line 280, in auto martini.optimization.findbeadpos
Valuefrror: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions, The detected shape was (23, 3) + inhomogeneous part
```

**Comment by supernovaZhangJiaXing** [comment]
> I don't recall getting this error. Can you provide more detail about the ValueError message?
> 
> Regarding the blow-up, it's likely because you're parametrizing an aromatic molecule with many constraints--these tend to be sensitive and may require careful equilibration (or fine-tuning of the parametrization with virtual sites, for instance).

Thank you! I also tried to use virtual sites and it works but sometimes not stable, so I tried auto_martini to get a better and more convinent workflow. The molecule I studied is [NLG-919](https://file.selleckchem.com/downloads/struct/NLG-919-chemical-structure-s7111.gif) with a slightly complicated tri-rings structure, so should it be treated by auto_martini or by my experence?

**Comment by tbereau** [comment]
Ideally auto_martini gives you a good initial guess. Given the highly aromatic nature of the molecule, it's likely that it needs a bit of manual fine-tuning.

**Comment by supernovaZhangJiaXing** [comment]
Thank you! I have understand.
