### ISSUE TITLE
pytest fail

### ISSUE THREAD

**Issue by yajairazepeda** [tbereau/auto_martini#43]
Hi, I try to run the pytest and I get the following errors:
```
FAILED auto_martini/tests/test_basic.py::test_auto_martini_run_sdf[sdf_file0-3] - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape af...
FAILED auto_martini/tests/test_basic.py::test_auto_martini_run_sdf[sdf_file1-5] - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape af...
FAILED auto_martini/tests/test_basic.py::test_auto_martini_run_smiles[N1=C(N)NNC1N-valid_GUA.top-GUA-2] - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape af...
FAILED auto_martini/tests/test_basic.py::test_auto_martini_run_smiles[CCC-valid_PRO.top-PRO-1] - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape af..
```
It is the auto_martini/optimization.pyx:280: ValueError in the four tests. Also, I get the same error with the example of guanazole.

Could you please help me?

**Comment by anabiman** [comment]
The problem seems to be coming from [vcclab.org](http://vcclab.org/) which has gone dark. This  service is used to estimate the water/octanol partition coefficient of the target cmpd. Any alternatives we should consider @tbereau ?

**Comment by anabiman** [comment]
The [Crippen](https://pubs.acs.org/doi/pdf/10.1021/ci990307l) method (implemented in [RDKit](https://www.rdkit.org/docs/source/rdkit.Chem.Crippen.html)) might be an option?

**Comment by tbereau** [comment]
Sorry for the late reply. I think `vcclab.org` is back on now. I wonder if the error shown has something to do with using `poetry` than `pip` (I was trying to move to `poetry`, but find it a bit unstable).

**Comment by whuuan** [comment]
This problem still exists. Is there any good solution?

**Comment by anabiman** [comment]
Fixed by [PR45](https://github.com/tbereau/auto_martini/pull/45).
