### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by DaVer15** [tbereau/auto_martini#48]
Hi! I tried to install auto-martini with conda but I receive this
"Error while finding module specification for 'auto_martini.__main__' (PackageNotFoundError: No package metadata was found for auto_martini)"
reinstall, update the necessary packages but I don't understand the problem.
Can you help me? 

Thank you!

**Comment by anabiman** [comment]
How are you installing with conda? Plz post the commands you're using.

**Comment by anabiman** [comment]
I tested conda installation on linux-64, osx-64, and osx-arm64 ... works just fine. You likely are not doing a pip install after activating the conda env.

**Comment by DaVer15** [comment]
in fact that's my problem, thanks for the advice, but now I'm getting
![Captura de Pantalla 2024-04-26 a la(s) 16 33 30](https://github.com/tbereau/auto_martini/assets/129212520/fc86b838-251d-4d04-b06a-327f072f78cd)

Sorry im new in this :c

**Comment by anabiman** [comment]
You need to share with me the sequence of commands you're using so I can reproduce the error. Also plz state the OS and conda version you're using.

**Comment by DaVer15** [comment]
I'm using macOS 12.7.4, Conda 24.3.0 and python 3.12.2
I download the .tar from GitHub, and then in terminal:
```
tar xzf auto_martini-0.2.0.tar
cd auto_martini-0.2.0
conda-lock -f pyproject.toml  -k explicit --filename-template auto_martini-py3.11.conda.lock
conda create --name YOURENV --file auto_martini-py3.11.conda.lock
conda activate YOURENV
pip3 install .
```
and got that error
sorry for the inconvenience

**Comment by anabiman** [comment]
Version detection requires you to work with a git repository. You need to clone the repo and not download the source code.

**Comment by anabiman** [comment]
I will close this issue if the problem has been resolved.
